### ISSUE TITLE
can't deploy to non-standard port

### ISSUE THREAD

**Issue by wodCZ** [hexojs/hexo-deployer-rsync#18]
_config.yml:

```
deploy:
  type: rsync
  host: 123.123.123.123
  user: admin
  root: web/example.com/public_html
  port: 1234
```

error:
```
ssh: connect to host 123.123.123.123 port 22: Operation timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ssh: connect to host 123.123.123.123 port 22: Operation timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]

    at ChildProcess.<anonymous> (/Users/wod/Sites/blog/node_modules/hexo-deployer-rsync/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

(I have firewall rule disabling connection on that port)

installed version: 0.1.2

**Comment by Xuanwo** [comment]
ref: https://github.com/hexojs/hexo-deployer-rsync/issues/20

Fixed, please use the latest code on github.
