### ISSUE TITLE
config file can't set port correctly

### ISSUE THREAD

**Issue by GroverChouT** [hexojs/hexo-deployer-rsync#24]
```
deploy:
  type: rsync
  host: ************
  user: root
  root: /var/www/*********
  port: 12488
  delete: true
  verbose: true
  ignore_errors: false
```
and then it will print
```
INFO  Deploying: rsync
ssh: connect to host ******** port 22: Network is unreachable
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ssh: connect to host ********* port 22: Network is unreachable
rsync: connection unexpectedly closed (0 bytes received so far) [sender]                                                
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]                                                   

    at ChildProcess.<anonymous> (/home/*******/node_modules/hexo-util/lib/spawn.js:37:17)       
    at emitTwo (events.js:106:13)                                                                                       
    at ChildProcess.emit (events.js:191:7)                                                                              
    at maybeClose (internal/child_process.js:877:16)                                                                    
    at Socket.<anonymous> (internal/child_process.js:334:11)                                                            
    at emitOne (events.js:96:13)                                                                                        
    at Socket.emit (events.js:188:7)                                                                                    
    at Pipe._handle.close [as _onclose] (net.js:498:12)                                                                 
FATAL ssh: connect to host ******** port 22: Network is unreachable
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
```
**If I downgrade to `0.1.1` everything gonna be ok**

**Comment by danschultzer** [comment]
Had the same issue, and reverted to 0.1.1. It's because of https://github.com/hexojs/hexo-deployer-rsync/pull/13 and https://github.com/hexojs/hexo-deployer-rsync/pull/15. They move the port outside the `-e` scope.

**Comment by tisswb** [comment]
same issue

**Comment by heartAndRain** [comment]
same thing here

**Comment by NoahDragon** [comment]
Doesn't https://github.com/hexojs/hexo-deployer-rsync/pull/15 fix it?

**Comment by danschultzer** [comment]
I just switched to master on package.json, and it works. @NoahDragon looks like v0.1.3 is not on npm?

#15 didn't fix it since it didn't change the remote-shell transport port, but the *rsync daemon port* which isn't used in this case. It seems to have been fixed in #17 (https://github.com/hexojs/hexo-deployer-rsync/commit/4e05a7281ece98e3d739099f028c8db4fb5d0678), though it's a weird fix. What happens now is that it'll use the rsync daemon on TCP if no port is defined, but if a port is defined it'll use ssh transport? In any case, if a port is defined it works as expected now on master.

**Comment by NoahDragon** [comment]
@danschultzer Thanks for the clarification. The npm version is maintained by @tommy351.

**Comment by stevenjoezhang** [comment]
New version released https://github.com/hexojs/hexo-deployer-rsync/releases/tag/1.0.0
I'm closing this issue. Please re-open if it is still outstanding.
