### ISSUE TITLE
rsync error: syntax or usage error (code 1) at main.c(1148) [Receiver=3.0.8]

### ISSUE THREAD

**Issue by akkuman** [hexojs/hexo-deployer-rsync#25]
```
deploy:
- type: rsync
  host: ********
  user: rsync
  root: /root/www/hexo/
  port: 873
  delete: true
  verbose: true
  ignore_errors: false
```
then hexo d 
```
INFO  Deploy done: git
INFO  Deploying: rsync
The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1148) [Receiver=3.0.8]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do
cs/troubleshooting.html
Error: The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1148) [Receiver=3.0.8]

    at ChildProcess.<anonymous> (F:\HEXO_BLOG\node_modules\hexo-util\lib\spawn.j
s:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (F:\HEXO_BLOG\node_modules\cross-spawn\lib\enoent.js
:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
FATAL The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1148) [Receiver=3.0.8]
````

**Comment by akkuman** [comment]
my os is windows,and i have added the rsync add the path.

**Comment by NoahDragon** [comment]
I also tried to use rsync under windows. There are many issues with it, so I use travis-ci to run the rsync. I would like to recommend to use rsync in Unix-ish system.
