### ISSUE TITLE
'rsync' is not recognized, 

### ISSUE THREAD

**Issue by eeemt** [hexojs/hexo-deployer-rsync#27]
> INFO  Deploying: rsync
'rsync' is not recognized as an internal or external command,
operable program or batch file.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: spawn rsync ENOENT
    at notFoundError (D:\hexo\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\hexo\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\hexo\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
FATAL spawn rsync ENOENT
Error: spawn rsync ENOENT
    at notFoundError (D:\hexo\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\hexo\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\hexo\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

 what shoud i do with this? 
thx

**Comment by NoahDragon** [comment]
Try to run `rsync` in the shell, does it prompt any info?

**Comment by eeemt** [comment]
> Try to run rsync in the shell, does it prompt any info?
I did not install rsync client before, thank you @NoahDragon

**Comment by NoahDragon** [comment]
Glad it could be easily resolved. 😄

**Comment by eeemt** [comment]
Thanks for your help @NoahDragon
