### ISSUE TITLE
[Solved]Unable to use rsync to deploy

### ISSUE THREAD

**Issue by ylbeethoven** [hexojs/hexo-deployer-rsync#33]
Hi Guys,

I think it is a common issue with rsync.

I've tried using Windows and Mac system but they are getting the same error.

INFO  Deploying: rsync
bash: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/io.c(453) [sender=2.6.9]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: bash: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/io.c(453) [sender=2.6.9]

    at ChildProcess.<anonymous> (/Users/FoFMM/Documents/Hexo/blog/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

I am currently using sftp but it is quite slow, can anyone please give me some advise?

I've no issue using SSH to go to my server, do I need to modify any information on my server side?

Thank you.

**Comment by ylbeethoven** [comment]
Problem solved...

I realised that you MUST install rsync on the server side as well.

Sorry, you can close this ticket now.
